---
# tasks file for snowagent
#
- name: Snowagent | Create Directories
  ansible.builtin.file:
    path: /opt/snow
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Snowagent | Add RPM gpg-key
  ansible.builtin.rpm_key:
    key: "{{ snowagent_baseurl }}snow_signing_key_pub.gpg"
  when: ansible_os_family == 'RedHat'

- name: Get Snowagent version
  ansible.builtin.command: /opt/snow/snowagent version
  register: snowagent_current_version 
  changed_when: false
  # changed: false # wir lesen nur die Version
  check_mode: false # damit wir auch in check Mode die Snowagent Version kriegen
  ignore_errors: true # wenn der Agent noch nicht installiert ist

- name: Snowagent | print Agent version RHEL
  ansible.builtin.debug:
    msg: "Current version: {{ snowagent_current_version.stdout }} update to version {{ snowagent_version }}"
  when: ansible_os_family == 'RedHat'

- name: Snowagent | Remove Agent if not the right Vesion RHEL
  ansible.builtin.dnf:
    name: "{{ snowagent_pkg }}"
    state: absent
  when: ansible_os_family == 'RedHat' and snowagent_version not in snowagent_current_version.stdout

- name: Snowagent | Install Agent RHEL
  ansible.builtin.dnf:
    name: "{{ snowagent_download_rpm }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Snowagent | Install Agent DEB
  ansible.builtin.apt:
    deb: "{{ snowagent_download_deb }}"
    force: yes
  when: ansible_os_family == 'Debian'

- name: Snowagent | Put the right SiteName in the configfile
  ansible.builtin.lineinfile:
    path: /opt/snow/snowagent.config
    line: "<SiteName>{{ snowagent_sitename }}</SiteName>"
    regexp: "<SiteName>unibe</SiteName>"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Snowagent | Put the Exclude Path in the configfile
  ansible.builtin.lineinfile:
    path: /opt/snow/snowagent.config
    line: "<Path>{{ item }}</Path>"
    regexp: "<Path>{{ item }}</Path>"
    insertafter: "<Exclude>"
    state: present
  with_items: "{{ snowagent_excludes }}"
  ignore_errors: "{{ ansible_check_mode }}"
