---
# tasks file for snowagent
#
- name: Snowagent | Create Directories
  ansible.builtin.file:
    path: /opt/snow
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Snowagent | Install Agent RHEL
  ansible.builtin.dnf:
    name: "{{ snowagent_download_rpm }}"
    disable_gpg_check: yes
  when: ansible_os_family == 'RedHat'
  tags: molecule-notest

- name: Snowagent | Install Agent DEB
  ansible.builtin.apt:
    deb: "{{ snowagent_download_deb }}"
    force: yes
  when: ansible_os_family == 'Debian'
  tags: molecule-notest

- name: Snowagent | Copy configfile
  ansible.builtin.template:
    src: snowagent.config.j2
    dest: /opt/snow/snowagent.config
    owner: root
    group: root
    mode: 0640
