---
# tasks file for snowagent
#

- name: Snowagent | Add RPM gpg-key
  ansible.builtin.rpm_key:
    key: "{{ snowagent_baseurl }}snow_signing_key_pub.gpg"
  when: ansible_os_family == 'RedHat'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Snowagent | Remove Agent if not the right Vesion RHEL
  ansible.builtin.dnf:
    name: "{{ snowagent_pkg }}"
    state: absent
  when: ansible_os_family == 'RedHat' and snowagent_current_version is defined and snowagent_current_version != snowagent_version

- name: Snowagent | print Versions RHEL
  ansible.builtin.debug:
    msg: "{{ snowagent_download_rpm }}"
  when: ansible_os_family == 'RedHat'

- name: Snowagent | print Agent RHEL
  ansible.builtin.debug:
    msg: "{{ snowagent_current_version }} / {{ snowagent_version }}"
  when: ansible_os_family == 'RedHat'

- name: Snowagent | Install Agent RHEL
  ansible.builtin.dnf:
    name: "{{ snowagent_download_rpm }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Snowagent | Install Agent DEB
  ansible.builtin.apt:
    deb: "{{ snowagent_download_deb }}"
    force: yes
  when: ansible_os_family == 'Debian'

- name: Snowagent | Put the right in the configfile
  ansible.builtin.lineinfile:
    path: /opt/snow/snowagent.config
    line: "<SiteName>{{ snowagent_sitename }}</SiteName>"
    regexp: "<SiteName>unibe</SiteName>"
    state: present
