---
- name: Uninstall Agent RHEL
  ansible.builtin.dnf:
    name: snowagent
    state: absent
  when: ansible_os_family == 'RedHat'

- name: Uninstall Agent DEB
  ansible.builtin.apt:
    name: snowagent
    state: absent
    purge: true
  when: ansible_os_family == 'Debian'

- name: Purge installation directory
  ansible.builtin.file:
    path: /opt/snow
    state: absent
