---
- name: Converge
  hosts: instance
  gather_facts: true
  tasks:
    - name: "Include unibeid.snowagent"
      ansible.builtin.include_role:
        name: "unibeid.snowagent"
      vars:
        snowagent_download_deb: "http://download/snowagent.deb"
        snowagent_download_rpm: "http://download/snowagent.rpm"
