---
- name: Verify
  hosts: instance
  gather_facts: false
  tasks:
    - name: Testing | Installation creates executable
      ansible.builtin.stat:
        path: /opt/snow/snowagent
      check_mode: true
      register: __testresult
      failed_when: not __testresult.stat.exists

    - name: Testing | Installation creates config
      ansible.builtin.stat:
        path: /opt/snow/snowagent.config
      check_mode: true
      register: __testresult
      failed_when: not __testresult.stat.exists
